// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/robux": {
    params: {};
  };
  "/robux/preorder": {
    params: {};
  };
  "/robux/preorder/form": {
    params: {};
  };
  "/robux/preorder/gamepass": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/robux" | "/robux/preorder" | "/robux/preorder/form" | "/robux/preorder/gamepass";
  };
  "./components/layouts/home.layout.tsx": {
    id: "components/layouts/home.layout";
    page: "/" | "/robux" | "/robux/preorder" | "/robux/preorder/form" | "/robux/preorder/gamepass";
  };
  "./pages/home.page.tsx": {
    id: "pages/home.page";
    page: "/";
  };
  "./pages/robux.page.tsx": {
    id: "pages/robux.page";
    page: "/robux";
  };
  "./pages/robux-preorder.page.tsx": {
    id: "pages/robux-preorder.page";
    page: "/robux/preorder";
  };
  "./pages/robux-preorder-form.page.tsx": {
    id: "pages/robux-preorder-form.page";
    page: "/robux/preorder/form";
  };
  "./pages/robux-preorder-gamepass.page.tsx": {
    id: "pages/robux-preorder-gamepass.page";
    page: "/robux/preorder/gamepass";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "components/layouts/home.layout": typeof import("./src/./components/layouts/home.layout.tsx");
  "pages/home.page": typeof import("./src/./pages/home.page.tsx");
  "pages/robux.page": typeof import("./src/./pages/robux.page.tsx");
  "pages/robux-preorder.page": typeof import("./src/./pages/robux-preorder.page.tsx");
  "pages/robux-preorder-form.page": typeof import("./src/./pages/robux-preorder-form.page.tsx");
  "pages/robux-preorder-gamepass.page": typeof import("./src/./pages/robux-preorder-gamepass.page.tsx");
};